### ISSUE TITLE
Why I get this error : error: ‘std::chrono’ has not been declared

### ISSUE THREAD

**Issue by jyzhang-bjtu** [tavildar/Polar#1]
The enviroment : gcc 4.9.2 

compile with  

g++ --std=c++11 main.cpp PolarCode.cpp PolarCode.h

**Comment by tavildar** [comment]
I am not sure.  It compiles on my system (MAC OS X with clang).  If this is the only error you are getting, then you can try removing the 2 or 3 lines that use std:chrono which is just used to time the program. 

There is also some discussion about the error here: http://stackoverflow.com/questions/27111756/g-4-8-stdchrono-undeclared

Please let me know if you are able to resolve the error.

**Comment by jyzhang-bjtu** [comment]
The compile command:  g++(clang++) --std=c++11 main.cpp PolarCode.cpp PolarCode.h
Platform : Debian 8.1, g++ 4.9.2 or clang++ 3.5
If I comment all the lines which contain std::chrono, the error became the follows,
PolarCode.cpp:35:5: error: ‘generate’ is not a member of ‘std’
PolarCode.cpp:36:5: error: ‘sort’ is not a member of ‘std’

It seems that the code depends on the MAC OS X or libc++. Because I do not have a Mac, I can not test it on OS X.

libc++ seems to implement more std functions or methods than libstdc++ (which is for g++).

The code maybe works well for MAC OS and can not be ported to Linux systems.

**Comment by tavildar** [comment]
Thanks for looking into it. There doesn't seem to be straight forward way of making code compatible with both libc++ and libstdc++ -- please let me know if I am wrong.

There is some discussion on http://libcxx.llvm.org/ on installing libc++ on linux if that helps.

I will update the ReadMe to reflect this.

**Comment by jyzhang-bjtu** [comment]
Done. I successfully compile the program on My debian 8.1 with g++ and libstdc++.

The program polarcode.cpp should include the following two lines:

#include < algorithm >
#include < chrono >

Thanks. 

I will test for the running results of the program.

buddy

**Comment by tavildar** [comment]
Great. I updated to include those import statements. The code compiled fine on my system with or without them.

I will close this issue. Please let me know if you encounter any other issues.

**Comment by vinay0486** [comment]
I found the following error while make
===================================================
mock_Util.cc: In function ‘void initialise_random(long unsigned int)’:
mock_Util.cc:299:21: error: ‘std::chrono’ has not been declared
  299 |         seed = std::chrono::system_clock::now().time_since_epoch().count();
===================================================
So I have added 
#include <chrono>
in mock_Util.cc file   (it depends on the project, I was working on a different project).
Now the problem gets solved.
======================================================
vinaysingh@vinaysingh-VirtualBox:~/delta/Delta-MOCK-master/Sources$ make all                                                                                            g++ -std=c++11 -O3 -c mock_Util.cc
g++ -std=c++11 -O3 -c mock_ClusteringProblem.cc
g++ -std=c++11 -O3 -c mock_Clustering.cc
g++ -std=c++11 -O3 -c mock_SolutionLocus.cc
g++ -std=c++11 -O3 -c mock_SolutionShort.cc
g++ -std=c++11 -O3 -c mock_SolutionSplit.cc
g++ -std=c++11 -O3 -c mock_Population.cc
g++ -std=c++11 -O3 -c mock_EvaluatorFull.cc
g++ -std=c++11 -O3 -c mock_BinaryOperator.cc
g++ -std=c++11 -O3 -c mock_UnaryOperator.cc
g++ -std=c++11 -O3 -c mock_Nsga2.cc
g++ -std=c++11 -O3 -c mock_EvaluatorDelta.cc
g++ -std=c++11 -O3 mock.o mock_Util.o mock_ClusteringProblem.o mock_Clustering.o mock_SolutionLocus.o mock_SolutionShort.o mock_SolutionSplit.o mock_Population.o mock_EvaluatorFull.o mock_BinaryOperator.o mock_UnaryOperator.o mock_Nsga2.o mock_EvaluatorDelta.o -o delta_mock
================================================================================

**Comment by vinay0486** [comment]
I found the following error while make
mock_Util.cc: In function ‘void initialise_random(long unsigned int)’:
mock_Util.cc:299:21: error: ‘std::chrono’ has not been declared
299 | seed = std::chrono::system_clock::now().time_since_epoch().count();
So I have added
#include "chrono"
in mock_Util.cc file (it depends on the project, I was working on a different project).
Now the problem gets solved.
vinaysingh@vinaysingh-VirtualBox:~/delta/Delta-MOCK-master/Sources$ make all g++ -std=c++11 -O3 -c mock_Util.cc
g++ -std=c++11 -O3 -c mock_ClusteringProblem.cc
g++ -std=c++11 -O3 -c mock_Clustering.cc
g++ -std=c++11 -O3 -c mock_SolutionLocus.cc
g++ -std=c++11 -O3 -c mock_SolutionShort.cc
g++ -std=c++11 -O3 -c mock_SolutionSplit.cc
g++ -std=c++11 -O3 -c mock_Population.cc
g++ -std=c++11 -O3 -c mock_EvaluatorFull.cc
g++ -std=c++11 -O3 -c mock_BinaryOperator.cc
g++ -std=c++11 -O3 -c mock_UnaryOperator.cc
g++ -std=c++11 -O3 -c mock_Nsga2.cc
g++ -std=c++11 -O3 -c mock_EvaluatorDelta.cc
g++ -std=c++11 -O3 mock.o mock_Util.o mock_ClusteringProblem.o mock_Clustering.o mock_SolutionLocus.o mock_SolutionShort.o mock_SolutionSplit.o mock_Population.o mock_EvaluatorFull.o mock_BinaryOperator.o mock_UnaryOperator.o mock_Nsga2.o mock_EvaluatorDelta.o -o delta_mock
