### ISSUE TITLE
error: expected expression

### ISSUE THREAD

**Issue by narges-dipir** [tavildar/Polar#2]
error: expected expression for two lines in PolarCode.cpp in Neatbeans.ide . first for :

`std::generate (std::begin(_channel_order_descending), std::end(_channel_order_descending), [&]{ return n_t++; });`

 and the same error for : 

`std::sort(  std::begin(_channel_order_descending),
                 std::end(_channel_order_descending),
                [&](int i1, int i2) { return channel_vec[_bit_rev_order.at(i1)] < channel_vec[_bit_rev_order.at(i2)]; } );`

**Comment by JYFredPark** [comment]
include "functional" library
