### ISSUE TITLE
[urgent]Question about the BLER point at 3dB

### ISSUE THREAD

**Issue by yuanhaiqiang2016** [tavildar/Polar#3]
Hello, tavildar,

It is my glad to see your polar code programming here. Thank you for your great job.
However, I do not know why when I run the polar code(MATLAB) with the programming provided by you.

--------------------------------
when [1] N=2048,R=0.5, crc_size=0; epsilon=0.32; list_vec = [1 2]; ebno_vec = [3]; max_err=30; max_runs=1500000 
-------------------------------
The BLER did not match with the Fig 1. in the paper of '''List decoding of polar code' by I.D, Vardy.
I don not know what exactly the mistaken was? Could you help me?
And may I ask you when you run the curves in ---- ------, what is the parameters you set before?

Thank you very much,
Looking forward to your reply.
[Could you reply via my email so that we can further contact conveniently  yuanhaiqiang2016@gmail.com]

Sincerely yours,
Hayman

**Comment by tavildar** [comment]
I had used the same parameters that are part of the code. Please let me know what BLER you are getting with those parameters compared to the paper.
