### ISSUE TITLE
Monte Carlo construction

### ISSUE THREAD

**Issue by 3160404008tyq** [tavildar/Polar#5]
hi Tavildar,

What is the reason for "if channels(channel_order(obj.info_length + obj.crc_size)) < 100" in the Monte Carlo algorithm? I really don't understand, Could you please help to check it?

**Comment by tavildar** [comment]
That statement is there to make sure that enough runs are used to get a reliable code. If a given channel has less than 100 errors -- for example if it has only 10 errors -- then the the probability of error estimate is unreliable. 

You can probably change that number to what you feel is more suitable. The number 100 was just my somewhat ad-hoc choice.

**Comment by 3160404008tyq** [comment]
Thank a lot for your reply!
Then, can I understand that this sentence is only from your many experiments, and there is no theoretical support?

**Comment by tavildar** [comment]
Yes -- from experiments. I don't know of any theoretical analysis of how many monte carlo runs are needed, so I used some heuristics that made sense to me.

**Comment by 3160404008tyq** [comment]
OK, I got it.Thank you again for your patience！
